name: bug
description: file a bug/issue
title: "[BUG] <title>"
labels: [Bug, Needs Triage]

body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        
        Thank you for reporting a bug! Please fill out the following template to help us better understand the issue and resolve it as quickly as possible.

  - type: checkboxes
    attributes:
      lable: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you found.
      options:
      - lable: I have searched existing issues
    validations:
      required: true

  - type: dropdown
    id: project_choice
    attributes:
      lable: For which project are you reporting this bug?
      options:
        - GraphQLConf
        - TWiG
        - meetings
        - Graph Traversal